//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUAHANGBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAO
    {
        public string maphieugiao { get; set; }
        public System.DateTime ngaylap { get; set; }
        public int soluonggiao { get; set; }
        public System.DateTime ngaygiaodukien { get; set; }
        public string tinhtranggiao { get; set; }
        public string maphieumuahang { get; set; }
        public string masach { get; set; }
        public string manhanvien { get; set; }
    
        public virtual CHITIETDATHANG CHITIETDATHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
