//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUAHANGBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
        }
    
        public string masach { get; set; }
        public string tensach { get; set; }
        public int soluonghienco { get; set; }
        public string dacdiem { get; set; }
        public string anhsanpham { get; set; }
        public string DVT { get; set; }
        public decimal dongia { get; set; }
        public string matheloai { get; set; }
        public string manhanvien { get; set; }
        public string manxb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual THELOAISACH THELOAISACH { get; set; }
    }
}
